// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Symbol struct {
	ID        int32          `json:"id"`
	CreatedTs sql.NullTime   `json:"created_ts"`
	Name      sql.NullString `json:"name"`
	Symbol    sql.NullString `json:"symbol"`
	Exchange  sql.NullString `json:"exchange"`
	AssetType sql.NullString `json:"asset_type"`
	Status    sql.NullBool   `json:"status"`
	DeletedTs sql.NullTime   `json:"deleted_ts"`
}
